# the source tree needs to be "booted" for this stack.yaml file to be usable:
#
# $ git submodule update --init --recursive
# $ ./utils/makePackages.sh
#

resolver: nightly-2018-05-14
packages:
  - .
  - ./lib/ghc-api-ghcjs
  - ./lib/ghci-ghcjs
  - ./lib/ghcjs-th
  - ./lib/haddock-api-ghcjs
  - ./lib/haddock-library-ghcjs
  - ./lib/template-haskell-ghcjs

extra-deps:
  - git: https://github.com/simonmar/ghc-paths.git
    commit: 6f3af8f98e538e08324bc97ceaf41d352e9d2732

